# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: True
  config:
    entity: seongbin
    project: lewm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False